Repository 3-PIUM/Back-end, pull requests merged in 2025-06, with the labels that each got.

#15 [FIX-14] Swgger api, 로그인 관련 기능 수정
  src/main/java/project/global/config/SwaggerConfig.java
  src/main/java/project/global/config/WebMvcConfig.java
Labels: bug

#12 [FS2-27 FEAT-11] : 장바구니 기능 구현
  build.gradle
  src/main/java/project/domain/cart/Cart.java
  src/main/java/project/domain/cart/controller/CartController.java
  src/main/java/project/domain/cart/dto/CartConverter.java
  src/main/java/project/domain/cart/dto/CartRequest.java
  src/main/java/project/domain/cart/dto/CartResponse.java
  src/main/java/project/domain/cart/repository/CartRepository.java
  src/main/java/project/domain/cart/service/CartService.java
  src/main/java/project/domain/cartitem/CartItem.java
  src/main/java/project/domain/cartitem/repository/CartItemRepository.java
  src/main/java/project/domain/item/Item.java
  src/main/java/project/domain/item/repository/ItemRepository.java
  src/main/java/project/domain/member/Member.java
  src/main/java/project/domain/member/repository/MemberRepository.java
  src/main/java/project/domain/member/service/MemberService.java
  src/main/java/project/domain/purchasehistory/PurchaseHistory.java
  src/main/java/project/domain/review/Review.java
  src/main/java/project/domain/wishlist/WishList.java
  src/main/java/project/global/config/SwaggerConfig.java
  src/main/java/project/global/response/status/ErrorStatus.java
  src/main/java/project/global/security/util/JwtUtil.java
Labels: enhancement

#18 [FIX-17] : 언어 Enum 값 변경
  src/main/java/project/domain/member/Member.java
  src/main/java/project/domain/member/dto/MemberConverter.java
  src/main/java/project/domain/member/enums/Area.java
  src/main/java/project/domain/member/enums/EnumUtil.java
  src/main/java/project/domain/member/enums/Gender.java
  src/main/java/project/domain/member/enums/Language.java
  src/main/java/project/domain/member/enums/PersonalType.java
  src/main/java/project/domain/member/enums/Role.java
  src/main/java/project/domain/member/enums/SkinType.java
  src/main/java/project/global/security/filter/JwtAuthFilter.java
  src/main/java/project/global/security/filter/LoginFilter.java
  src/main/java/project/global/security/util/JwtUtil.java
Labels: bug, enhancement

#22 [FEAT-21] 피부 설문조사에 관한 기능 추가
  src/main/java/project/domain/mbti/MbtiQuestion.java
  src/main/java/project/domain/mbti/SkinAxis.java
  src/main/java/project/domain/mbti/Step.java
  src/main/java/project/domain/mbti/controller/MbtiQuestionController.java
  src/main/java/project/domain/mbti/dto/MbtiQuestionConverter.java
  src/main/java/project/domain/mbti/dto/MbtiQuestionRequest.java
  src/main/java/project/domain/mbti/dto/MbtiQuestionResponse.java
  src/main/java/project/domain/mbti/repository/MbtiQuestionRepository.java
  src/main/java/project/domain/mbti/service/MbtiQuestionService.java
  src/main/java/project/global/response/status/ErrorStatus.java
Labels: enhancement

#20 [FEAT-19] : 구매내역 관련 기능 추가
  src/main/java/project/domain/purchasehistory/PurchaseHistory.java
  src/main/java/project/domain/purchasehistory/controller/PurchaseHistoryController.java
  src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryConverter.java
  src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryResponse.java
  src/main/java/project/domain/purchasehistory/repository/PurchaseHistoryRepository.java
  src/main/java/project/domain/purchasehistory/service/PurchaseHistoryService.java
Labels: enhancement

#27 [FIX-21] 피부 설문조사 다국어 기능 추가
  build.gradle
  src/main/java/project/domain/mbti/MbtiQuestion.java
  src/main/java/project/domain/mbti/controller/MbtiQuestionController.java
  src/main/java/project/domain/mbti/repository/MbtiQuestionRepository.java
  src/main/java/project/domain/mbti/service/MbtiQuestionService.java
Labels: enhancement

#28 [FSE-42 FEAT] 리뷰 기능 구현
  build.gradle
  src/main/java/project/domain/common/BaseEntity.java
  src/main/java/project/domain/review/Review.java
  src/main/java/project/domain/review/controller/ReviewController.java
  src/main/java/project/domain/review/dto/ReviewConverter.java
  src/main/java/project/domain/review/dto/ReviewRequest.java
  src/main/java/project/domain/review/dto/ReviewResponse.java
  src/main/java/project/domain/review/repository/ReviewRepository.java
  src/main/java/project/domain/review/service/ReviewService.java
  src/main/java/project/domain/reviewimage/ReviewImage.java
  src/main/java/project/domain/reviewimage/repository/ReviewImageRepository.java
  src/main/java/project/domain/wishlist/controller/WishListController.java
  src/main/java/project/domain/wishlist/dto/WishListConverter.java
  src/main/java/project/domain/wishlist/dto/WishListResponse.java
  src/main/java/project/domain/wishlist/service/WishListService.java
  src/main/java/project/global/config/S3Config.java
  src/main/java/project/global/response/status/ErrorStatus.java
  src/main/java/project/global/s3/service/S3Uploader.java
Labels: enhancement

#33 [FEAT] 찜,장바구니 관련 DTO에 아이템 이미지 추가 및 관련 서비스 코드 수정
  src/main/java/project/domain/cart/Cart.java
  src/main/java/project/domain/cart/controller/CartController.java
  src/main/java/project/domain/cart/dto/CartConverter.java
  src/main/java/project/domain/cart/dto/CartResponse.java
  src/main/java/project/domain/cart/service/CartService.java
  src/main/java/project/domain/category/Category.java
  src/main/java/project/domain/company/Company.java
  src/main/java/project/domain/item/Item.java
  src/main/java/project/domain/itemimage/ItemImage.java
  src/main/java/project/domain/itemimage/enums/ImageType.java
  src/main/java/project/domain/itemimage/repository/ItemImageRepository.java
  src/main/java/project/domain/reviewimage/ReviewImage.java
  src/main/java/project/domain/wishlist/controller/WishListController.java
  src/main/java/project/domain/wishlist/dto/WishListConverter.java
  src/main/java/project/domain/wishlist/dto/WishListResponse.java
  src/main/java/project/domain/wishlist/repository/WishlistRepository.java
  src/main/java/project/domain/wishlist/service/WishListService.java
  src/main/java/project/global/config/S3Config.java
  src/main/java/project/global/util/ImageUtil.java
Labels: FEAT, FIX

#35 [FEAT-34] : 사용자 프로필 사진 수정 기능 추가
  src/main/java/project/domain/member/Member.java
  src/main/java/project/domain/member/controller/MemberController.java
  src/main/java/project/domain/member/service/MemberService.java
  src/main/java/project/domain/review/service/ReviewService.java
  src/main/java/project/global/s3/util/S3Uploader.java
Labels: FEAT

#48 [FS2-66 FEAT] 장바구니 옵션 추가
  src/main/java/project/domain/cart/controller/CartController.java
  src/main/java/project/domain/cart/dto/CartConverter.java
  src/main/java/project/domain/cart/dto/CartRequest.java
  src/main/java/project/domain/cart/dto/CartResponse.java
  src/main/java/project/domain/cart/service/CartService.java
  src/main/java/project/domain/cartitem/CartItem.java
  src/main/java/project/domain/cartitem/repository/CartItemRepository.java
  src/main/java/project/domain/itemoption/repository/ItemOptionRepository.java
Labels: FEAT

#50 [FS2-67 FEAT] 카테고리 별 상품 조회 및 검색 키워드에 따른 상품 조회 구현
  src/main/java/project/domain/cart/controller/CartController.java
  src/main/java/project/domain/cart/service/CartService.java
  src/main/java/project/domain/cartitem/repository/CartItemRepository.java
  src/main/java/project/domain/item/controller/ItemController.java
  src/main/java/project/domain/item/controller/ItemSearchController.java
  src/main/java/project/domain/item/dto/ItemConverter.java
  src/main/java/project/domain/item/dto/ItemSearchConverter.java
  src/main/java/project/domain/item/dto/ItemSearchResponse.java
  src/main/java/project/domain/item/repository/ItemRepository.java
  src/main/java/project/domain/item/service/ItemSearchService.java
  src/main/java/project/domain/member/Member.java
  src/main/java/project/domain/purchasehistory/PurchaseHistory.java
Labels: FEAT

#56 [FCS-69 FIX] : 구매내역 조회 기능 수정
  src/main/java/project/domain/purchasehistory/PurchaseHistory.java
  src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryConverter.java
  src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryResponse.java
Labels: FIX

#63 [FIX 62] 축관련 타입 enum 분리
  src/main/java/project/domain/mbti/SkinAxis.java
  src/main/java/project/domain/mbti/Step.java
  src/main/java/project/domain/member/Member.java
  src/main/java/project/domain/member/dto/MemberConverter.java
  src/main/java/project/global/enums/skin/AxisType.java
Labels: FIX

#68 [FIX] mbti 설문 내용 조회 기능수정
  src/main/java/project/domain/mbti/MbtiQuestion.java
  src/main/java/project/domain/mbti/SkinAxis.java
  src/main/java/project/domain/mbti/controller/MbtiQuestionController.java
  src/main/java/project/domain/mbti/dto/MbtiQuestionConverter.java
  src/main/java/project/domain/mbti/dto/MbtiQuestionResponse.java
  src/main/java/project/domain/mbti/repository/MbtiQuestionRepository.java
  src/main/java/project/domain/mbti/service/MbtiQuestionService.java
  src/main/java/project/global/enums/skin/AxisType.java
  src/main/java/project/global/enums/skin/SkinType.java
  src/main/java/project/global/util/QuestionUtil.java
Labels: FIX

#74 [FS2-82 FEAT] AI 요약 테이블 아이템 옵션 필드 추가
  src/main/java/project/domain/aisummary/AiSummary.java
  src/main/java/project/domain/item/dto/ItemConverter.java
  src/main/java/project/domain/item/dto/ItemResponse.java
Labels: FEAT

#77 [FEAT] ai 요약테이블 필드 추가
  .gitignore
  src/main/java/project/domain/aisummary/AiSummary.java
  src/main/java/project/domain/item/dto/ItemConverter.java
  src/main/java/project/domain/item/dto/ItemResponse.java
  src/main/resources/application.yml
Labels: FEAT

#80 [FS2-82 FEAT] 조회, 결제, 장바구니 등록 로그 Kafka+ELK 연동
  .gitignore
  docker-compose.yml
  filebeat/filebeat.yml
  logstash/pipeline/logstash.conf
  src/main/java/project/domain/cart/controller/CartController.java
  src/main/java/project/domain/cart/service/CartService.java
  src/main/java/project/domain/item/service/ItemService.java
  src/main/java/project/domain/review/service/ReviewService.java
  src/main/java/project/global/config/KafkaProducerConfig.java
  src/main/java/project/global/kafka/dto/cart/CartEventDTO.java
  src/main/java/project/global/kafka/dto/purchase/PurchaseEventDTO.java
  src/main/java/project/global/kafka/dto/view/ViewEventDTO.java
  src/main/java/project/global/kafka/service/cart/CartLogConsumer.java
  src/main/java/project/global/kafka/service/cart/CartLogProducer.java
  src/main/java/project/global/kafka/service/purchase/PurchaseEventConsumer.java
  src/main/java/project/global/kafka/service/purchase/PurchaseLogProducer.java
  src/main/java/project/global/kafka/service/purchase/PurchaseLogService.java
  src/main/java/project/global/kafka/service/view/ViewLogConsumer.java
  src/main/java/project/global/kafka/service/view/ViewLogService.java
  src/main/resources/logback-spring.xml
Labels: FEAT

#82 [FS2-83 FEAT] 피부 고민별 상품 조회
  build.gradle
  src/main/java/project/domain/item/controller/ItemSearchController.java
  src/main/java/project/domain/item/dto/ItemSearchConverter.java
  src/main/java/project/domain/item/dto/ItemSearchResponse.java
  src/main/java/project/domain/item/repository/ItemDynamicSort.java
  src/main/java/project/domain/item/repository/ItemRepository.java
  src/main/java/project/domain/item/service/ItemSearchService.java
  src/main/java/project/domain/review/Review.java
  src/main/java/project/global/config/QueryDSLConfig.java
  src/main/resources/logback-spring.xml
Labels: FEAT

#91 [FEAT] 인기 급상승 제품 Top10 조회
  src/main/java/project/domain/item/controller/ItemRecommendController.java
  src/main/java/project/domain/item/controller/ItemSearchController.java
  src/main/java/project/domain/item/dto/ItemSearchResponse.java
  src/main/java/project/domain/item/dto/converter/ItemConverter.java
  src/main/java/project/domain/item/dto/converter/ItemRecommendConverter.java
  src/main/java/project/domain/item/dto/converter/ItemSearchConverter.java
  src/main/java/project/domain/item/service/ItemRecommendService.java
  src/main/java/project/domain/item/service/ItemSearchService.java
  src/main/java/project/domain/item/service/ItemService.java
  src/main/java/project/domain/trenditem/TrendItem.java
  src/main/java/project/domain/trenditem/dto/TrendItemConverter.java
  src/main/java/project/domain/trenditem/dto/TrendItemDTO.java
  src/main/java/project/domain/trenditem/repository/TrendItemRepository.java
  src/main/java/project/global/redis/controller/RedisController.java
  src/main/java/project/global/redis/dto/ItemViewScoreDTO.java
  src/main/java/project/global/redis/service/ItemViewRedis.java
  src/main/java/project/global/redis/service/popular/PopularCacheService.java
  src/main/java/project/global/redis/service/popular/PopularItemsBatchService.java
  src/main/java/project/global/redis/service/trend/TrendCacheService.java
  src/main/java/project/global/redis/service/trend/TrendItemBatchService.java
Labels: FEAT

#95 [FIX-83] : 챗봇 기능 수정
  src/main/java/project/domain/itemimage/repository/ItemImageRepository.java
  src/main/java/project/global/chat/controller/ChatController.java
  src/main/java/project/global/chat/dto/ChatResponseDTO.java
  src/main/java/project/global/chat/service/ChatService.java
Labels: FIX

#98 [FEAT] ML에서 만든 데이터 서빙 API 구현
  src/main/java/project/domain/areapopularitem/repository/AreaPopularItemRepository.java
  src/main/java/project/domain/item/controller/ItemRecommendController.java
  src/main/java/project/domain/item/dto/ItemRecommendResponse.java
  src/main/java/project/domain/item/dto/converter/ItemRecommendConverter.java
  src/main/java/project/domain/item/service/ItemRecommendService.java
  src/main/java/project/domain/member/Member.java
  src/main/java/project/domain/member/repository/MemberRepository.java
  src/main/java/project/domain/relatedpurchaseitem/RelatedPurchaseItem.java
  src/main/java/project/domain/relatedpurchaseitem/repository/RelatedPurchaseItemRepository.java
  src/main/java/project/domain/relatedviewitem/RelatedViewItem.java
  src/main/java/project/domain/relatedviewitem/repository/RelatedViewItemRepository.java
Labels: FEAT
